% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={NCGR NISE-Bioinformatics},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{NCGR NISE-Bioinformatics}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{national-center-for-genome-resources}{%
\chapter*{National Center for Genome Resources}\label{national-center-for-genome-resources}}
\addcontentsline{toc}{chapter}{National Center for Genome Resources}

This publication was supported by an Institutional Development Award (IDeA) from the National Institute of General Medical Sciences of the National Institutes of Health under grant number P20GM103451.

\hypertarget{license-and-copyright}{%
\section*{License and Copyright}\label{license-and-copyright}}
\addcontentsline{toc}{section}{License and Copyright}

Creative Commons Attribution-NonCommercial-NoDerivatives 4.0
\url{https://creativecommons.org/licenses/by-nc-nd/4.0/}

© 2023 National Center for Genome Resources

\hypertarget{linux}{%
\chapter{Linux}\label{linux}}

\textbf{Linux operating system (OS) and Bourne-Again SHell (bash) command-language basics}

\hypertarget{a-little-shell-aka-the-prompt-is-the-command-line-interface}{%
\section{A little shell\ldots{} aka the \$ prompt is the command line interface}\label{a-little-shell-aka-the-prompt-is-the-command-line-interface}}

\begin{itemize}
\tightlist
\item
  A shell is a user interface to the operating system.

  \begin{itemize}
  \tightlist
  \item
    CLI (Command Line Interface)
  \item
    GUI (Graphical User Interface)
  \end{itemize}
\item
  Bourne-Again SHell (bash) is a Unix shell and command language
\item
  Each command drives a program or script by talking to the Operating System
  (Linux)
\end{itemize}

\hypertarget{directory-structure}{%
\section{Directory Structure}\label{directory-structure}}

\includegraphics[width=1\textwidth,height=\textheight]{./Figures/DirectoryStructure.png}

In a Finder window, you would see this:

\includegraphics[width=0.6\textwidth,height=\textheight]{./Figures/FinderWindow.png}

\hypertarget{find-the-shell-in-system-youll-use-to-log-into-the-ncgrs-server}{%
\section{Find the shell in system you'll use to log into the NCGR's server}\label{find-the-shell-in-system-youll-use-to-log-into-the-ncgrs-server}}

\begin{itemize}
\tightlist
\item
  For \textbf{Windows}: search for MobaXterm from the start menu.

  \begin{itemize}
  \tightlist
  \item
    It may be useful to drag the terminal icon to the \textbf{desktop} for easier access in the future.
  \end{itemize}
\item
  For \textbf{Mac}: search for ``terminal'' in the bar located in the Launchpad (rocket icon in the taskbar).

  \begin{itemize}
  \tightlist
  \item
    It may be useful to drag the terminal icon into the \textbf{Dock} for easier access in the future.
  \end{itemize}
\end{itemize}

\hypertarget{log-on-to-logrus-server}{%
\section{Log on to logrus server}\label{log-on-to-logrus-server}}

Enter the following command to log on to logrus:

\begin{itemize}
\tightlist
\item
  substitute \textbf{your} personal username in for ``username''
\end{itemize}

\begin{verbatim}
ssh -p 44111 username@gateway.training.ncgr.org
\end{verbatim}

Notes:

\begin{itemize}
\tightlist
\item
  Because we're logging in remotely, the -p option is required to specify port 44111.
\item
  If you're prompted to confirm the connection, say ``yes'', then enter your password.
\end{itemize}

\hypertarget{now-that-i-logged-on-where-am-i}{%
\section{Now that I logged on, where am I?}\label{now-that-i-logged-on-where-am-i}}

You're at the command line interface of the logrus analysis server!

To the left of the command prompt, you should see something like this:

\begin{itemize}
\tightlist
\item
  {[}\href{mailto:eprice@logrus}{\nolinkurl{eprice@logrus}} \textasciitilde{]}\$
\end{itemize}

Command \textbf{output} is shown after the ``\#\#'' in this document.

\hypertarget{part-i-basic-topics}{%
\section{Part I: Basic Topics}\label{part-i-basic-topics}}

\hypertarget{understanding-directories}{%
\subsection{Understanding Directories}\label{understanding-directories}}

print working directory (pwd), mkdir (make directory), and list contents (ls)

\begin{verbatim}
pwd
\end{verbatim}

\begin{verbatim}
## /home/eprice
\end{verbatim}

\begin{itemize}
\tightlist
\item
  This is your ``home'' directory.
\end{itemize}

Now, create a dir under your home directory for this linux class:

\begin{verbatim}
mkdir linuxc

ls
\end{verbatim}

\begin{verbatim}
## linuxc
\end{verbatim}

\hypertarget{listing-options}{%
\subsection{Listing options}\label{listing-options}}

using the ls command

\begin{itemize}
\tightlist
\item
  \textbf{l}ong list:
\end{itemize}

\begin{verbatim}
ls -l
\end{verbatim}

\begin{verbatim}
## total 4
## drwxrwxr-x 2 eprice eprice 4096 Aug 17 22:50 linuxc
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \textbf{l}ong list, by \textbf{t}ime, \textbf{r}everse order -old to new:
\end{itemize}

\begin{verbatim}
ls -ltr
\end{verbatim}

\begin{verbatim}
## total 4
## drwxrwxr-x 2 eprice eprice 4096 Aug 17 22:50 linuxc
\end{verbatim}

\hypertarget{navigation}{%
\subsection{Navigation}\label{navigation}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  ``\textbf{c}hange \textbf{d}irectory'' to the directory you made
\end{enumerate}

\begin{itemize}
\tightlist
\item
  where \textasciitilde{} is shorthand for your home directory
\end{itemize}

\begin{verbatim}
cd ~/linuxc

pwd
\end{verbatim}

\begin{verbatim}
## /home/eprice/linuxc
\end{verbatim}

\hypertarget{files-creating-with-touch-command}{%
\subsection{Files: creating with touch command}\label{files-creating-with-touch-command}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Create a file
\end{enumerate}

\begin{verbatim}
touch newfile.txt

ls -l
\end{verbatim}

\begin{verbatim}
## total 0
## -rw-rw-r-- 1 eprice eprice 0 Aug 17 22:50 newfile.txt
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Change to your home dir
\end{enumerate}

\begin{verbatim}
cd ~ 

pwd
\end{verbatim}

\begin{verbatim}
## /home/eprice
\end{verbatim}

\hypertarget{history-command}{%
\subsection{History command}\label{history-command}}

lists the commands you have entered

\begin{verbatim}
history
\end{verbatim}

\begin{verbatim}
## 17 ls -ltr
## 18 cd ../linuxc
## 19 ls -ltr
## 20 history
\end{verbatim}

Scroll through recent commands with the up and down arrows.

To perform a command from the list by number:

\begin{verbatim}
!17
\end{verbatim}

To perform the last command you made:

\begin{verbatim}
!!
\end{verbatim}

\hypertarget{files-creating-by-redirecting-standard-out}{%
\subsection{Files: creating by redirecting standard out}\label{files-creating-by-redirecting-standard-out}}

redirect operator \textbf{\textgreater{}}

To send output to a file instead of standard out:

\begin{itemize}
\tightlist
\item
  standard out is just the terminal
\end{itemize}

\begin{verbatim}
history > history.txt

ls -l
\end{verbatim}

\begin{verbatim}
## total 4
## -rw-rw-r-- 1 eprice eprice 0    Aug 17 22:50 history.txt
## drwxrwxr-x 2 eprice eprice 4096 Aug 17 22:50 linuxc
\end{verbatim}

\begin{verbatim}
cat history.txt
\end{verbatim}

\begin{verbatim}
## 17 ls -ltr
## 18 cd ../linuxc
## 19 ls -ltr
## 20 history
## 21 ls -ltr
## 20 history > history
\end{verbatim}

Now you have a file with your commands!

\hypertarget{file-name-completion-with-tab}{%
\subsection{File name completion with tab}\label{file-name-completion-with-tab}}

To autocomplete remainder of file name instead of typing it all in:

\begin{itemize}
\tightlist
\item
  cat h\ldots(press tab)

  \begin{itemize}
  \tightlist
  \item
    cat history
  \end{itemize}
\item
  prevents typos and saves time
\end{itemize}

\hypertarget{files-moving-files-from-one-filename-to-another}{%
\subsection{Files: moving files from one filename to another}\label{files-moving-files-from-one-filename-to-another}}

\textbf{m}o\textbf{v}ing ``mv'' command

\hypertarget{syntax-mv-sourcefilename-destinationfilename}{%
\subsubsection*{Syntax: mv sourcefilename destinationfilename}\label{syntax-mv-sourcefilename-destinationfilename}}
\addcontentsline{toc}{subsubsection}{Syntax: mv sourcefilename destinationfilename}

\begin{verbatim}
mv history.txt history_file.txt

ls -l
\end{verbatim}

\begin{verbatim}
## total 4
## -rw-rw-r-- 1 eprice eprice 0    Aug 17 22:50 history_file.txt 
## drwxrwxr-x 2 eprice eprice 4096 Aug 17 22:50 linuxc
\end{verbatim}

\hypertarget{files-copying-files-from-one-filename-to-another}{%
\subsection{Files: copying files from one filename to another}\label{files-copying-files-from-one-filename-to-another}}

\textbf{c}o\textbf{p}ying ``cp'' command

\hypertarget{syntax-cp-sourcefilename-destinationfilename}{%
\subsubsection*{Syntax: cp sourcefilename destinationfilename}\label{syntax-cp-sourcefilename-destinationfilename}}
\addcontentsline{toc}{subsubsection}{Syntax: cp sourcefilename destinationfilename}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Change back to the linuxc directory:
\end{enumerate}

\begin{verbatim}
cd ~/linuxc
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Make a ``back up'' copy of a file in your working directory:
\end{enumerate}

\begin{verbatim}
cp ~/linuxc/newfile.txt newfile_bu.txt
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Check if the newly copied file is there:
\end{enumerate}

\begin{verbatim}
ls
\end{verbatim}

\begin{verbatim}
## newfile_bu.txt
## newfile.txt
\end{verbatim}

\hypertarget{files-securely-copying-files-between-your-laptop-and-logrus}{%
\subsection{Files: securely copying files between your laptop and logrus}\label{files-securely-copying-files-between-your-laptop-and-logrus}}

\textbf{s}ecure \textbf{c}o\textbf{p}y ``scp'' command

\begin{itemize}
\tightlist
\item
  a secure way to copy files to/from a server while you're working on an outside network

  \begin{itemize}
  \tightlist
  \item
    like from your home or starbucks to logrus and vice versa
  \end{itemize}
\end{itemize}

\hypertarget{syntax-scp-options-sourcepath-destinationpath}{%
\subsubsection*{Syntax: scp {[}options{]} sourcepath destinationpath}\label{syntax-scp-options-sourcepath-destinationpath}}
\addcontentsline{toc}{subsubsection}{Syntax: scp {[}options{]} sourcepath destinationpath}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Create a file to copy
\end{enumerate}

\begin{verbatim}
touch scp_test.txt
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{itemize}
\tightlist
\item
  \textbf{Mac} users

  \begin{itemize}
  \tightlist
  \item
    open a \textbf{local} terminal
  \item
    do \textbf{not} connect it to logrus
  \end{itemize}
\item
  \textbf{Windows} users

  \begin{itemize}
  \tightlist
  \item
    open a new MobaXterm session (shell)
  \end{itemize}
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Run the scp command from your \textbf{local} terminal window:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  to \textbf{download} the file \textbf{to your computer} from logrus
\item
  the last period means that the destination is your working directory
\end{itemize}

\begin{verbatim}
scp -P 44111 <user>@gateway.training.ncgr.org:~/linuxc/scp_test.txt .
\end{verbatim}

Note: When you designate a port with secure copy (scp), you use a capital P.

You will be prompted for your logrus password if not using MobaXterm.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{3}
\item
  Check to see if the file you copied from logrus is on \textbf{your} computer!
\item
  Now \textbf{upload} a file \textbf{to logrus} from your computer
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Again, run the scp command from your \textbf{local} terminal window:
\end{itemize}

\begin{verbatim}
scp -P 44111 scp_test.txt <user>@gateway.training.ncgr.org:~/linuxc
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  Check to see if the file you copied from your computer is on \textbf{logrus}!
\end{enumerate}

\hypertarget{files-and-directories-removing-files-is-deleting-files}{%
\subsection{Files and directories: removing files is deleting files}\label{files-and-directories-removing-files-is-deleting-files}}

\textbf{r}e\textbf{m}oving ``rm'' command

\hypertarget{syntax-rm-options-filename}{%
\subsubsection*{Syntax: rm {[}options{]} filename}\label{syntax-rm-options-filename}}
\addcontentsline{toc}{subsubsection}{Syntax: rm {[}options{]} filename}

\begin{verbatim}
rm -i newfile_bu.txt
\end{verbatim}

\begin{verbatim}
## rm: remove regular empty file newfile_bu.txt?
\end{verbatim}

Enter ``yes'' or ``y'' in response to the question:

\begin{verbatim}
yes

ls -l
\end{verbatim}

\begin{verbatim}
## total 0
## -rw-rw-r-- 1 eprice eprice 0 Aug 17 22:50 newfile.txt
\end{verbatim}

At this point everyone should have the above in their linuxc class directory.

\hypertarget{tool-box-how-to-abort-a-commandprocess}{%
\subsection{Tool box: How to abort a command/process}\label{tool-box-how-to-abort-a-commandprocess}}

Hold ``control'' key then hit ``c'' key, then release.

\begin{itemize}
\tightlist
\item
  Control-key often referred to as CTRL.
\end{itemize}

Let's say you type a command and nothing happens; it hangs.
This can happen when the syntax doesn't make sense.
Good time for CTRL c

\begin{verbatim}
cat
\end{verbatim}

If you can't execute commands, then CTRL c

\begin{verbatim}
## ^C
\end{verbatim}

You should be returned to your prompt: {[}\href{mailto:username@logrus}{\nolinkurl{username@logrus}} linuxc{]}\$

\hypertarget{part-ii-advanced-topics}{%
\section{PART II: Advanced Topics}\label{part-ii-advanced-topics}}

\hypertarget{files-symbolic-links-and-the-soft-link--s}{%
\subsection{Files: Symbolic links and the soft link (-s)}\label{files-symbolic-links-and-the-soft-link--s}}

\hypertarget{syntax-ln--s-fileyouwanttolinkpointto-nameyouwanttogiveit}{%
\subsubsection*{Syntax: ln -s FileYouWantToLink/PointTo NameYouWantToGiveIt}\label{syntax-ln--s-fileyouwanttolinkpointto-nameyouwanttogiveit}}
\addcontentsline{toc}{subsubsection}{Syntax: ln -s FileYouWantToLink/PointTo NameYouWantToGiveIt}

\begin{verbatim}
ln -s /home/eprice/covid.fasta covid.fasta

ls -l
\end{verbatim}

\begin{verbatim}
## total 0
## lrwxrwxrwx 1 eprice eprice 26 Aug 17 22:50 covid.fasta -> /home/eprice/covid.fasta 
## -rw-rw-r-- 1 eprice Aug 17 22:50 newfile.txt
\end{verbatim}

\hypertarget{understanding-a-fasta-file-format}{%
\subsection{Understanding a fasta file format}\label{understanding-a-fasta-file-format}}

Fasta files (.fasta or .fa) contain one or more sequences, each preceded by a \textbf{header} starting with ``\textgreater{}''.

Show only the \textbf{first 10 lines} of a file with ``head'' command:

\begin{verbatim}
head covid.fasta
\end{verbatim}

\begin{verbatim}
## >NC_045512.2 |Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, co
## ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCT
## GTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACT
## CACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATC
## TTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTT
## CGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAAC
## ACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGG
## AGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGG
## CTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAA
## ACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACT
\end{verbatim}

Now show only the \textbf{last 10 lines} of a file using the ``tail'' command:

\begin{verbatim}
tail covid.fasta
\end{verbatim}

\begin{verbatim}
## TATTGACGCATACAAAACATTCCCACCAACAGAGCCTAAAAAGGACAAAAAGAAGAAGGC
## TGATGAAACTCAAGCCTTACCGCAGAGACAGAAGAAACAGCAAACTGTGACTCTTCTTCC
## TGCTGCAGATTTGGATGATTTCTCCAAACAATTGCAACAATCCATGAGCAGTGCTGACTC
## AACTCAGGCCTAAACTCATGCAGACCACACAAGGCAGATGGGCTATATAAACGTTTTCGC
## TTTTCCGTTTACGATATATAGTCTACTCTTGTGCAGAATGAATTCTCGTAACTACATAGC
## ACAAGTAGATGTAGTTAACTTTAATCTCACATAGCAATCTTTAATCAGTGTGTAACATTA
## GGGAGGACTTGAAAGAGCCACCACATTTTCACCGAGGCCACGCGGAGTACGATCGAGTGT
## ACAGTGAACAATGCTAGGGAGAGCTGCCTATATGGAAGAGCCCTAATGTGTAAAATTAAT
## TTTAGTAGTGCTATCCCCATGTGATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAA
## AAAAAAAAAAAAAAAAAAAAAAA
\end{verbatim}

\hypertarget{the-pipe-operator-will-redirect-output-of-a-command-to-another-command.}{%
\subsubsection*{The pipe operator will redirect output of a command to another command.}\label{the-pipe-operator-will-redirect-output-of-a-command-to-another-command.}}
\addcontentsline{toc}{subsubsection}{The pipe operator will redirect output of a command to another command.}

Use the pipe operator to redirect ``cat'' output to ``head'':

\begin{itemize}
\tightlist
\item
  The symbol ``\textbar{}'' denotes a pipe
\end{itemize}

\begin{verbatim}
cat covid.fasta | head
\end{verbatim}

\begin{verbatim}
## >NC_045512.2 |Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, co
## ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCT
## GTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACT
## CACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATC
## TTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTT
## CGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAAC
## ACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGG
## AGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGG
## CTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAA
## ACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACT
\end{verbatim}

\begin{verbatim}
cat covid.fasta | tail
\end{verbatim}

\begin{verbatim}
## TATTGACGCATACAAAACATTCCCACCAACAGAGCCTAAAAAGGACAAAAAGAAGAAGGC
## TGATGAAACTCAAGCCTTACCGCAGAGACAGAAGAAACAGCAAACTGTGACTCTTCTTCC
## TGCTGCAGATTTGGATGATTTCTCCAAACAATTGCAACAATCCATGAGCAGTGCTGACTC
## AACTCAGGCCTAAACTCATGCAGACCACACAAGGCAGATGGGCTATATAAACGTTTTCGC
## TTTTCCGTTTACGATATATAGTCTACTCTTGTGCAGAATGAATTCTCGTAACTACATAGC
## ACAAGTAGATGTAGTTAACTTTAATCTCACATAGCAATCTTTAATCAGTGTGTAACATTA
## GGGAGGACTTGAAAGAGCCACCACATTTTCACCGAGGCCACGCGGAGTACGATCGAGTGT
## ACAGTGAACAATGCTAGGGAGAGCTGCCTATATGGAAGAGCCCTAATGTGTAAAATTAAT
## TTTAGTAGTGCTATCCCCATGTGATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAA
## AAAAAAAAAAAAAAAAAAAAAAA
\end{verbatim}

\hypertarget{understanding-fastq-fq-file-format}{%
\subsection{Understanding fastq (fq) file format}\label{understanding-fastq-fq-file-format}}

Fastq files contain sequence reads and associated \textbf{meta data}.

\begin{verbatim}
ln -s /home/fds/unix_basics/SP1.fq SP1.fq

ls -ltr
\end{verbatim}

\begin{verbatim}
## total 0
## -rw-rw-r-- 1 eprice eprice 0 Aug 17 22:50 newfile.txt
## lrwxrwxrwx 1 eprice eprice 26 Aug 17 22:50 covid.fasta -> /home/eprice/covid.fasta 
## lrwxrwxrwx 1 eprice eprice Aug 17 22:50 SP1.fq -> /home/fds/unix_basics/SP1.fq
\end{verbatim}

Tail the last 4 lines:

\begin{verbatim}
tail -n 4 SP1.fq
\end{verbatim}

\begin{verbatim}
## @cluster_834:UMI_TTAAGG
## AGGGTGGGGGATCACATTTATTGTATTGAGG 
## +
## =A=@AB===>4?A=??EEB?EB@C?ECB=A?
\end{verbatim}

A fastq file has 4 lines per record:

\begin{itemize}
\tightlist
\item
  The header; starts with ``@''
\item
  The sequence
\item
  Throwaway line; begins with ``+''
\item
  Phred-scaled quality scores
\end{itemize}

\hypertarget{what-is-the-difference-between-this-and-a-fasta-file}{%
\paragraph*{What is the difference between this and a fasta file?}\label{what-is-the-difference-between-this-and-a-fasta-file}}
\addcontentsline{toc}{paragraph}{What is the difference between this and a fasta file?}

\hypertarget{using-grep-global-regular-expression-print-to-extract-metrics}{%
\subsection{Using grep (global regular expression print) to extract metrics}\label{using-grep-global-regular-expression-print-to-extract-metrics}}

Grep will output the lines containing a provided expression.

\hypertarget{syntax-grep-options-expression-filename}{%
\subsubsection*{Syntax: grep {[}options{]} ``expression'' filename}\label{syntax-grep-options-expression-filename}}
\addcontentsline{toc}{subsubsection}{Syntax: grep {[}options{]} ``expression'' filename}

\begin{verbatim}
grep ">" covid.fasta
\end{verbatim}

\begin{verbatim}
## >NC_045512.2 |Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, co
## >MT627325.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT622319.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568634.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568635.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568636.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568637.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568638.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568639.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568640.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT568641.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407649.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407650.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407651.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407652.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407653.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407654.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407655.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407656.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407657.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407658.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT407659.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT534630.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT510727.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT510728.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079843.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079844.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079845.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079846.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079847.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079848.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079849.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079850.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079851.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079852.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079853.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT079854.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT446312.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT412134.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT396241.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT039874.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT281577.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291826.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291827.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291828.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291829.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291830.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291831.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291832.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291833.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291834.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291835.2 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT291836.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT259226.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT259227.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT259228.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT259229.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT259230.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT259231.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253696.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253697.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253698.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253699.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253700.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253701.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253702.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253703.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253704.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253705.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253706.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253707.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253708.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253709.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT253710.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT226610.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT121215.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT135041.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT135042.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT135043.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT135044.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT123290.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT123291.2 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT123292.2 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT123293.2 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT093631.2 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT049951.1 |Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/huma
## >MT039873.1 |Severe acute respiratory syndrome coronavirus 2 isolate HZ-1, complete
## >MT019529.1 |Severe acute respiratory syndrome coronavirus 2 isolate BetaCoV/Wuhan/I
## >MT019530.1 |Severe acute respiratory syndrome coronavirus 2 isolate BetaCoV/Wuhan/I
## >MT019531.1 |Severe acute respiratory syndrome coronavirus 2 isolate BetaCoV/Wuhan/I
## >MT019532.1 |Severe acute respiratory syndrome coronavirus 2 isolate BetaCoV/Wuhan/I
## >MT019533.1 |Severe acute respiratory syndrome coronavirus 2 isolate BetaCoV/Wuhan/I
## >MN996527.1 |Severe acute respiratory syndrome coronavirus 2 isolate WIV02, complete
## >MN996528.1 |Severe acute respiratory syndrome coronavirus 2 isolate WIV04, complete
## >MN996529.1 |Severe acute respiratory syndrome coronavirus 2 isolate WIV05, complete
## >MN996530.1 |Severe acute respiratory syndrome coronavirus 2 isolate WIV06, complete
## >MN996531.1 |Severe acute respiratory syndrome coronavirus 2 isolate WIV07, complete
## >MN988668.1 |Severe acute respiratory syndrome coronavirus 2 isolate 2019-nCoV WHU01
## >MN988669.1 |Severe acute respiratory syndrome coronavirus 2 isolate 2019-nCoV WHU02
## >MN938384.1 |Severe acute respiratory syndrome coronavirus 2 isolate 2019-nCoV_HKU-S
## >MN975262.1 |Severe acute respiratory syndrome coronavirus 2 isolate 2019-nCoV_HKU-S
## >MN908947.3 |Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, com
\end{verbatim}

Adding the ``-c'' option counts the number of lines containing a match

\begin{itemize}
\tightlist
\item
  \textbf{not} the number of matches!
\end{itemize}

\begin{verbatim}
grep -c ">" covid.fasta
\end{verbatim}

\begin{verbatim}
## 102
\end{verbatim}

The ``-v'' option reverses the grep search, which is the first step towards finding the total length of sequences

\begin{verbatim}
grep -v ">" covid.fasta
\end{verbatim}

Use c to halt the overflow of output.

We can add in the pipe operator to redirect our output to the ``wc'' command.

The output shows the number of newline characters, followed by line count and total character count.

\begin{verbatim}
grep -v ">" covid.fasta | wc
\end{verbatim}

wc: prints newline, word, and byte counts for each file:

\begin{verbatim}
## 50812 50812 3096018
\end{verbatim}

Let's trim out the newline characters with ``tr -d'' before doing the word count:

\begin{verbatim}
grep -v ">" covid.fasta | tr -d ’\n’ | wc
\end{verbatim}

\begin{verbatim}
##       0       1 3045206
\end{verbatim}

\hypertarget{working-with-compressed-files}{%
\subsection{Working with compressed files}\label{working-with-compressed-files}}

Powerful Z commands (zcat)

\begin{itemize}
\tightlist
\item
  p.~1 of 2
\end{itemize}

Let's copy another file:

\begin{verbatim}
cp /home/fds/unix_basics/table1.txt.gz /home/<user>/linuxczcat table1.txt.gz
\end{verbatim}

\begin{verbatim}
## 1, Justin Timberlake, Title 545, Price $7.30
## 2, Taylor Swift, Title 723, Price $7.90
## 3, Mick Jagger, Title 610, Price $7.90
## 4, Lady Gaga, Title 118, Price $7.30
## 5, Johnny Cash, Title 482, Price $6.50
## 6, Elvis Presley, Title 335, Price $7.30
## 7, John Lennon, Title 271, Price $7.90
## 8, Michael Jackson, Title 373, Price $5.50
\end{verbatim}

\begin{verbatim}
zgrep "Jagger" table1.txt.gz
\end{verbatim}

\begin{verbatim}
## 3, Mick Jagger, Title 610, Price $7.90
\end{verbatim}

!! = last command

:s = substitute /word1/with word2

\begin{verbatim}
!!:s/Jagger/John
\end{verbatim}

\begin{verbatim}
## 5, Johnny Cash, Title 482, Price $6.50
## 7, John Lennon, Title 271, Price $7.90
\end{verbatim}

\hypertarget{start-and-end-symbols}{%
\subsection{Start \^{} and end \$ symbols}\label{start-and-end-symbols}}

Powerful Z commands (zgrep)

\begin{itemize}
\tightlist
\item
  p.~2 of 2
\end{itemize}

Display all the lines that start with 8:

\begin{verbatim}
zgrep "^8" table1.txt.gz
\end{verbatim}

\begin{verbatim}
## 8, Michael Jackson, Title 373, Price $5.50
\end{verbatim}

Display all the lines that end with 50:

\begin{verbatim}
zgrep "50$" table1.txt.gz
\end{verbatim}

\begin{verbatim}
## 5, Johnny Cash, Title 482, Price $6.50
## 8, Michael Jackson, Title 373, Price $5.50
\end{verbatim}

\hypertarget{files-parsing-and-creating-data-subsets}{%
\subsection{Files: parsing and creating data-subsets}\label{files-parsing-and-creating-data-subsets}}

p.1 of 5

Be sure you are in linuxc directory (as usual)

AWK command

\begin{itemize}
\tightlist
\item
  \textbf{A}ho, \textbf{W}einberger and \textbf{K}ernighan

  \begin{itemize}
  \tightlist
  \item
    the authors of the language
  \end{itemize}
\end{itemize}

General syntax:

\begin{itemize}
\tightlist
\item
  awk 'pattern \{action\}' input-file

  \begin{itemize}
  \tightlist
  \item
    output goes to standard out=terminal
  \end{itemize}
\item
  awk 'pattern \{action\}' input-file \textgreater{} output-file

  \begin{itemize}
  \tightlist
  \item
    or send to an output file
  \end{itemize}
\end{itemize}

\hypertarget{exercise}{%
\subsubsection*{Exercise:}\label{exercise}}
\addcontentsline{toc}{subsubsection}{Exercise:}

How many fields does the 1st row of table1.txt have?

Let's look at the 1st row of table1.txt:

1, Justin Timberlake, Title 545, Price \$7.30

How many fields does it have?

\hypertarget{files-parsing-and-creating-data-subsets-1}{%
\subsection{Files: parsing and creating data-subsets}\label{files-parsing-and-creating-data-subsets-1}}

p.~2 of 5

\begin{verbatim}
gunzip table1.txt.gz

cat table1.txt
\end{verbatim}

\begin{verbatim}
## 1, Justin Timberlake, Title 545, Price $7.30
## 2, Taylor Swift, Title 723, Price $7.90
## 3, Mick Jagger, Title 610, Price $7.90
## 4, Lady Gaga, Title 118, Price $7.30
## 5, Johnny Cash, Title 482, Price $6.50
## 6, Elvis Presley, Title 335, Price $7.30
## 7, John Lennon, Title 271, Price $7.90
## 8, Michael Jackson, Title 373, Price $5.50
\end{verbatim}

\begin{verbatim}
awk '{print $1 $3 $5}' table1.txt
\end{verbatim}

\begin{verbatim}
## 1,Timberlake,545,
## 2,Swift,723,
## 3,Jagger,610,
## 4,Gaga,118,
## 5,Cash,482,
## 6,Presley,335,
## 7,Lennon,271,
## 8,Jackson,373,
\end{verbatim}

\hypertarget{files-parsing-and-creating-data-subsets-2}{%
\subsection{Files: parsing and creating data-subsets}\label{files-parsing-and-creating-data-subsets-2}}

p.~3 of 5

Using field separator command -F

\begin{verbatim}
cat table1.txt
\end{verbatim}

\begin{verbatim}
## 1, Justin Timberlake, Title 545, Price $7.30
## 2, Taylor Swift, Title 723, Price $7.90
## 3, Mick Jagger, Title 610, Price $7.90
## 4, Lady Gaga, Title 118, Price $7.30
## 5, Johnny Cash, Title 482, Price $6.50
## 6, Elvis Presley, Title 335, Price $7.30
## 7, John Lennon, Title 271, Price $7.90
## 8, Michael Jackson, Title 373, Price $5.50
\end{verbatim}

\begin{verbatim}
awk -F, '{print $3}' table1.txt
\end{verbatim}

\begin{verbatim}
##  Title 545
##  Title 723
##  Title 610
##  Title 118
##  Title 482
##  Title 335
##  Title 271
##  Title 373
\end{verbatim}

\hypertarget{files-parsing-and-creating-data-subsets-3}{%
\subsection{Files: parsing and creating data-subsets}\label{files-parsing-and-creating-data-subsets-3}}

p.~4 of 5: Conditional awk

Time to really watch for syntax errors!

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  Statements inside the curly brackets \{statement\} are called a block.
\item
  If you put a conditional expression in front of a block with with ==, the statement inside the block will be executed \textbf{only if} the condition is \textbf{true}.
\item
  The whole awk command is inside ' '.
\end{enumerate}

\begin{itemize}
\tightlist
\item
  For example:

  \begin{itemize}
  \tightlist
  \item
    awk `\$7==``\$7.30''\{print \$3\}' table1.txt
  \end{itemize}
\item
  The condition is:

  \begin{itemize}
  \tightlist
  \item
    if \$7==``\$7.30''
  \item
    meaning if the element at column 7 is equal to ``\$7.30'', then execute statement(s) in the block \{print \$3\}.
  \end{itemize}
\end{itemize}

\hypertarget{revisiting-table1-and-previous-awk-command}{%
\subsection{\texorpdfstring{Revisiting table1 and \emph{previous} awk command}{Revisiting table1 and previous awk command}}\label{revisiting-table1-and-previous-awk-command}}

p.~5 of 5

\begin{verbatim}
awk '$7=="$7.30" {print $3}' table1.txt
\end{verbatim}

\begin{verbatim}
## Timberlake,
## Gaga,
## Presley,
\end{verbatim}

\includegraphics[width=0.6\textwidth,height=\textheight]{./Figures/awk.png}

\hypertarget{files-stream-editor-sed}{%
\subsection{\texorpdfstring{Files: \textbf{S}tream \textbf{ED}itor (sed)}{Files: Stream EDitor (sed)}}\label{files-stream-editor-sed}}

text substitution

\hypertarget{syntax-sed-spatternreplacement}{%
\subsubsection*{Syntax: sed s/pattern/replacement}\label{syntax-sed-spatternreplacement}}
\addcontentsline{toc}{subsubsection}{Syntax: sed s/pattern/replacement}

Examples:

\begin{verbatim}
echo "it’s a trap" | sed s/ra/ar/
\end{verbatim}

\begin{verbatim}
## it’s a tarp
\end{verbatim}

Say you want to change all price occurrences of \$7.90 to \$8.90 from table1.txt, and save the changes to a new file.

You can do this with sed.

\begin{verbatim}
sed 's/7.90/8.90/' table1.txt > table2.txt
\end{verbatim}

Use cat to display the contens of the new file:

\begin{verbatim}
cat table2.txt
\end{verbatim}

\begin{verbatim}
## 1, Justin Timberlake, Title 545, Price $7.30
## 2, Taylor Swift, Title 723, Price $8.90
## 3, Mick Jagger, Title 610, Price $8.90
## 4, Lady Gaga, Title 118, Price $7.30
## 5, Johnny Cash, Title 482, Price $6.50
## 6, Elvis Presley, Title 335, Price $7.30
## 7, John Lennon, Title 271, Price $8.90
## 8, Michael Jackson, Title 373, Price $5.50
\end{verbatim}

\hypertarget{the-bash-for-loop}{%
\subsection{The Bash ``for'' Loop}\label{the-bash-for-loop}}

Suppose we want to run a command for a \textbf{group of files} in a directory. We can use a for loop to target all of them at once.

\hypertarget{syntax-for-variablename-in-filenameexpression-do-command-variablename-done}{%
\subsubsection*{Syntax: for variablename in filenameexpression; do command \$\{variablename\}; done}\label{syntax-for-variablename-in-filenameexpression-do-command-variablename-done}}
\addcontentsline{toc}{subsubsection}{Syntax: for variablename in filenameexpression; do command \$\{variablename\}; done}

\begin{verbatim}
for file in *; do echo ${file}; done
\end{verbatim}

\begin{verbatim}
## covid.fasta
## newfile.txt
## SP1.fq
## table1.txt
## table2.txt
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The part up to the first semicolon targets every file in the working directory with the ``*'' wildcard
\item
  The second part will sequentially echo each file in the working directory
\item
  The third part is required to terminate the loop
\end{itemize}

\hypertarget{help-with-command-syntax}{%
\subsection{Help with command syntax}\label{help-with-command-syntax}}

If you forget details of a certain command, documentation can easily be found with a web search.

There is also cheat sheet on the weebly site under Supplemental Documents.

\hypertarget{exercises}{%
\section{Exercises}\label{exercises}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Using awk, print to output the first names of artists with album prices over \$7.50 from ta- ble1.txt. Then redirect this output to a file named homework\_1.txt
\item
  Using sed, replace all commas with semicolons in table1.txt. Save this to a file named home- work\_2.txt
\item
  Piping history to grep, show all commands you've used with the expression ``ls''. Save this to a file named homework\_3.txt
\item
  Piping cat to wc -l on the history text file made during the tutorial, count the number of lines in it.
\item
  Using scp, download table1.txt to your own machine. Check it's there, then upload it back to logrus.
\end{enumerate}

\hypertarget{part-iii}{%
\section{PART III}\label{part-iii}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  Log on to logrus server
\item
  Enter the following command to log on to logrus:
\end{enumerate}

\begin{verbatim}
ssh -p 44111 username@gateway.training.ncgr.org
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Don't forget to substitute \textbf{your} personal username in
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Make a new directory under \textbf{your home directory}:
\end{enumerate}

\begin{verbatim}
mkdir fastq_files
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Enter into the new directory:
\end{enumerate}

\begin{verbatim}
cd fastq_files
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  Move the fastq file from yesterday to the present working directory:
\end{enumerate}

\begin{verbatim}
mv ~/linuxc/SP1.fq .

ls -ltr
\end{verbatim}

\begin{verbatim}
## total 0
## lrwxrwxrwx 1 elavelle elavelle 28 Aug 17 22:50 SP1.fq -> /home/fds/unix_basics/SP1.f
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  How can we count the number of records in a fastq file?
\end{enumerate}

\begin{verbatim}
grep -c "@cluster" SP1.fq
\end{verbatim}

\begin{verbatim}
## 250
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
  If you want to determine the number of lines in a file, you can use the ``wc'' command.
\end{enumerate}

\begin{verbatim}
cat SP1.fq | wc -l
\end{verbatim}

\begin{verbatim}
## 1000
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{7}
\tightlist
\item
  Why does the first command output 250 and the second 1000?
\end{enumerate}

\hypertarget{more-exercises}{%
\section{More Exercises}\label{more-exercises}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  With one command, send a copy of table1.txt in the linuxc directory to your home directory with the name table1\_bu.txt
\item
  Print to standard output the last line of table1.txt
\item
  Use a loop to count the number of lines in all files in the linuxc directory.
\item
  Print to standard output the last names of music artists with album prices less than or equal to \$7.30
\item
  Create a file with only the accession numbers of the sequences contained in the covid.fasta file (with no additional spaces or symbols).
\end{enumerate}

\hypertarget{parsing-data}{%
\chapter{Parsing Data}\label{parsing-data}}

\hypertarget{practice}{%
\section{Practice}\label{practice}}

Let's practice with a small file. Make sure you are in a \textbf{screen}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Make a directory under your home directory called ``parse''.
\item
  Go into that directory.
\item
  Copy the file ``pandemics.csv'' from this directory: ``/home/jm/linux\_practice/'' to the directory you just made.
\item
  Take a look at the file.
\item
  Sort by year an put it into a new file called ``sort.pandemic.csv''
  Note that you will need to change the delimiter to a comma (-t), tell it to sort numerically (-n), and tell it which column to sort (-k) sort -t, -n -k3 pandemics.csv \textgreater{} sort.pandemics.csv
\item
  Pull out all the instances that mention plague
  Note that grep is case sensitive by default so you might want to use the -i flag to make it case insensitive in case the is inconsistent
\item
  Pull out all the instance of the flu
\item
  Let's count the number of each type of pathogen (column 2). You could do this with a series of grep commands but with a big file you might not know all the possible pathogens and it would get tedious. So let's do this in a step-wise fashion and make sure each piece is as expected, then pipe it into the next step.\\
  a. First pull out column 2 using awk or cut\\
  b. Get the unique values (make sure you ``sort'' before you ``uniq'' or you will only deredundify adjacent identical values).\\
  c.~Get the count (hint: add -c to the uniq step)
\item
  Grab and count the organisms for the instances that mention plague
\end{enumerate}

Hint: It is the same as \#8 except you need to grab the plague lines first. When you put a command after the pipe it will read in the output of the previous command so only use the file name on the first command.

Click for All Answers

Note that there are often several ways to do things in linux and not all methods are shown.

\begin{verbatim}
1. mkdir ~/parse

2. cd ~/parse

3. cp /home/jm/linux_practice/pandemics.csv . [Don't forget the space and period at the end; the period says to name it the same thing.]

4. cat table1.diff.txt [you could also use more, less, head, tail, or other commands]

5. sort -t, -nk 3 pandemics.csv > sort.pandemics.csv

6. grep -i plague sort.pandemics.csv

7. grep -i flu sort.pandemics.csv

8. awk -F, '{print $2}' sort.pandemics.csv | sort | uniq -c
     [Note that you can also use: "cut -d, -f2 pandemics.csv" for the first step]

9. grep -i plague sort.pandemics.csv | awk -F, '{print $2}' | sort | uniq -c
\end{verbatim}

\hypertarget{our-world-in-data}{%
\section{Our World in Data}\label{our-world-in-data}}

Now let's use the data from ``Our World In Data''. For things that are new, we have added some in-line answers but before you reveal the answer, try it yourself first using the hints provided.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\item
  Copy the file ``owid-covid-data.csv'' from this directory: ``/home/jm/linux\_practice/'' to your ``parse'' directory.
\item
  Make sure you are in the ``parse'' directory.
\item
  How many rows are in the file? Use wc -l (wc = word count, -l = lines)
\end{enumerate}

Click for Answer

\begin{verbatim}
  wc -l owid-covid-data.csv
\end{verbatim}

\hfill\break

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  How many columns? There is a special variable, NF, in awk, which prints the number of fields
\end{enumerate}

Note: this will print the number of fields in each row. You can hit ctrl-c if you don't want to go through the whole file

Click for Answer

\begin{verbatim}
  awk -F, '{print NF}' owid-covid-data.csv
\end{verbatim}

\hfill\break

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Let's look at hospital\_beds\_per\_thousand (column 60). We also need to get the location (country) from column 3 and the date from column 4. We'll pipe it into less so that we can scroll through it (to get out of less, hit ``q'').
\end{enumerate}

Click for Answer

\begin{verbatim}
  cut -d, -f 3,4,60 owid-covid-data.csv | less
\end{verbatim}

\hfill\break

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\item
  There are lots of dates for each country. Let's limit it to early in the pandemic (2020-01-03), which is the first available date. Put it into a file called ``beds.2020-01-03.csv'' so we don't have to keep generating it.
\item
  What country had the least beds per thousand on 2020-01-03 and which has the most? Hint: Sort by the number of beds and pipe it into less.
\end{enumerate}

Note: Some lines have missing data and will sort at the top of the file so you will have to scroll down.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{16}
\tightlist
\item
  How many beds were there in the United States on 2020-01-03?
\end{enumerate}

Hint: There is a ``United States'' and a ``United States Virgin Islands''. To avoid getting the latter, have the match end with a comma. Also, require grep to start the match at the beginning of the line (\^{}). It is good practice to be specific when using grep.

Click for Answer

\begin{verbatim}
  grep "^United States," beds.2020-01-03.csv
\end{verbatim}

\hfill\break

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{17}
\tightlist
\item
  How many beds were there in your three countries on 2020-01-03?
\end{enumerate}

If your countries don't have data on that date, go back to the original file and see if you can find data for any date.

Hint: we'll use the extended version of grep which will allow us to search all 3 at once. Use the -E flag and put the things you are searching for in double quotes, seperated by pipes.

Click for Answer

\begin{verbatim}
  grep -E "^Sweden,|^Norway,|^Denmark," beds.2020-01-03.csv
\end{verbatim}

\hfill\break

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{18}
\item
  Create a file that has only the United States data for beds with the same three columns we have been using. Call it usbeds.csv. We'll use this file for the questions below.
\item
  Get the number of beds in the United States for each day in 2020.
\item
  Get the number of beds in the United States for the first COVID wave (March through September 2020).
\end{enumerate}

Hint: Use sed to remove the dashes then awk with \$2\textgreater=20200301\&\&\$2\textless=20200930.

Click for Answer

sed `s/-//g' usbeds.csv \textbar{} awk `\$2\textgreater=20200301\&\&\$2\textless=20200930\{print\}'

\hfill\break

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{21}
\tightlist
\item
  BONUS: Get the average number of beds in the United States for the first COVID wave (March through September 2020). This is a tough one. See if you can understand the code.
\end{enumerate}

Click for Answer

sed `s/-//g' usbeds.csv \textbar{} sed `s/-//g' \textbar awk -F, `\$2\textgreater=20200301\&\&\$2\textless=20200930\{SUM+=\$3;CNT+=1\}END\{print SUM/CNT\}'

\hfill\break

Click for All Answers

\begin{verbatim}
10. cp /home/jm/linux_practice/owid-covid-data.csv . 

11. pwd [If you aren't in that directory you can: "cd ~/parse"]

12. wc -l owid-covid-data.csv

13. awk -F, '{print NF}' owid-covid-data.csv

14. cut -d, -f 3,4,60 owid-covid-data.csv | less

15. cut -d, -f 3,4,60 owid-covid-data.csv | grep 2020-01-03 > beds.2020-01-03.csv

16. sort -t, -n -k3 beds.2020-01-03.csv | less

    Least: Mali,2020-01-03,0.1
    
    Most: Monaco,2020-01-03,13.8

17. grep "^United States," beds.2020-01-03.csv

18. grep -E "^Sweden,|^Norway,|^Denmark," beds.2020-01-03.csv

19. cut -d, -f 3,4,60 owid-covid-data.csv | grep "^United States," > usbeds.csv

20. grep 2020 usbeds.csv

21. sed 's/-//g' usbeds.csv | sed 's/-//g' |awk -F, '$2>=20200301&&$2<=20200930{print}'

22. sed 's/-//g' usbeds.csv | sed 's/-//g' |awk -F, '$2>=20200301&&$2<=20200930{SUM+=$3;CNT+=1}END{print SUM/CNT}'

\end{verbatim}

\hypertarget{practice-with-your-3-countries}{%
\section{Practice with your 3 countries}\label{practice-with-your-3-countries}}

Now practice on your own. Choose another variable and see if there are any interesting differences between your 3 countries. Explore at least 3 other variables.

Hint: You can look at the variables by heading the first line of the file.

\begin{verbatim}
    head -1 owid-covid-data.csv
\end{verbatim}

Hint: If you prefer to have them each on their own line you can use sed to replace the commas with hard returns. Make sure to use the global ``g'' at the end so that every comma is replaced and not just the first one on each line.

\begin{verbatim}
    head -1 owid-covid-data.csv | sed 's/,/\n/g'
\end{verbatim}

Hint: awk will also print out the row number for you (which corresponds to the column number for that variable in the original file). The NR variable is a special awk variable that will print the row.

\begin{verbatim}
    head -1 owid-covid-data.csv | sed 's/,/\n/g' |awk '{print NR "\t" $1}'
\end{verbatim}

\hypertarget{ncbi-sars-cov-2-genome-sequences}{%
\chapter{NCBI SARS-CoV-2 Genome Sequences}\label{ncbi-sars-cov-2-genome-sequences}}

\hypertarget{getting-sequences-from-ncbi}{%
\section{Getting Sequences from NCBI}\label{getting-sequences-from-ncbi}}

See pdf.

\hypertarget{exploring-sequence-files}{%
\section{Exploring Sequence Files}\label{exploring-sequence-files}}

Let's start with the Denmark, Norway, Sweden files. Make sure you are in the NCBIdata directory.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Grab just the sequence header lines.
\item
  How many sequences are there for Denmark?
\item
  Grab just the country out of the fasta headers
\end{enumerate}

Your headers should have these fields, delimitted by a pipe (make sure you put the pipes in quotes so it doesn't interpret it):

\begin{verbatim}
  1) Accession
  2) Genbank Title
  3) Collection Date
  4) Country
  5) GEO Location
  6) Length
  7) Pangolin (variant)
  8) SRA Accession
  9) Sequence Type
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  How many sequences are there for each country?
\end{enumerate}

Hint: Use sort then uniq -c (the latter gets counts of all the unique values).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\item
  How many sequences are there for each Geo Location? Some will just have the country there but others will have more granular information.
\item
  How many sequences are there for each pangolin variant? What is the dominant one? Look up more information for the dominant lineage at this site: \url{https://cov-lineages.org/lineage_list.html}
\item
  Haw many sequences are there for each pangolin variant in each country?
\item
  How many sequences are not blank in the collection data field?
\end{enumerate}

\begin{verbatim}
Hint: Use "^$" in grep to find lines that have nothing between the start "^" and end "$" of the line.
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  What is the first and last date in your sequence file?
\end{enumerate}

Hint: There are lots of different ways to do this, some of which involve more scrolling than others. Here is one strategy that just gets the earliest and latest dates. Do each step and check it then pipe it into the next step.

\begin{verbatim}
  1) Get the header lines
  2) Grab the collection data column (#3)
  3) Remove blanks
  4) Sort numerically: sort -n
  5) grab the first and last lines--you need the parentheses: (head -1; tail -1)
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Find the first and last collection date in your sequence file for each country. Try to use a for loop. Since we haven't used these much I'll put an answer here for you.
\end{enumerate}

Note: for some reason, the (head -1; tail -1) trick doesn't seem to work inside a for loop. So, do the earliest date first. Then use the up arrow to get the command back and alter it for the latest date.

Click for Answer

\begin{verbatim}
    for i in 'Denmark' 'Norway' 'Sweden'; do
      echo $i
      grep $i sequences.fasta | cut -f 3 -d '|' | grep -v "^$" | sort -n | head -1
  done
\end{verbatim}

\hfill\break

Click for All Answers

Note that there are often several ways to do things in linux and not all methods are shown.

\begin{verbatim}
1. grep '>' sequences.fasta

2. grep -c 'Denmark' sequences.fasta

14 sequences for Denmark

3. grep '>' sequences.fasta | cut -f 4 -d '|'

4. grep '>' sequences.fasta | cut -f 4 -d '|' | sort |uniq -c

     14 Denmark
     
      5 Norway
      
    616 Sweden

5. grep '>' sequences.fasta | cut -f 5 -d '|' | sort |uniq -c

     14 Denmark
     
      2 Norway
      
      3 Norway: Bergen
      
    566 Sweden
    
      1 Sweden:Goteborg
      
     44 Sweden: Orebro
     
      5 Sweden:Stockholm, Sweden

6. grep '>' sequences.fasta | cut -f 7 -d '|' | sort |uniq -c

The dominant pangolin variant is B.1 which occurs 429 times.

7. grep '>' sequences.fasta | cut -f 4,7 -d '|' | sort |uniq -c

8. grep '>' sequences.fasta | cut -f 3 -d '|' |grep -c "^$"

9. grep '>' sequences.fasta | cut -f 3 -d '|' | grep -v "^$" | sort -n | (head -1; tail -1)

10. The first is for the earliest date and the second for the latest date.

for i in 'Denmark' 'Norway' 'Sweden'; do
  echo $i
  grep $i sequences.fasta | cut -f 3 -d '|' | grep -v "^$" | sort -n | head -1
done

for i in 'Denmark' 'Norway' 'Sweden'; do
  echo $i
  grep $i sequences.fasta | cut -f 3 -d '|' | grep -v "^$" | sort -n | tail -1
done
\end{verbatim}

\hypertarget{practice-with-your-3-countries-1}{%
\section{Practice with your 3 countries}\label{practice-with-your-3-countries-1}}

Run through these exercises again with your 3 countries and record the answers in your project powerpoint or elsewhere. We'll talk about what you found.

\hypertarget{plotting}{%
\section{Plotting}\label{plotting}}

We'll plot some of the information about our sequences using R on the command line and the ggplot2 library. Get into a screen if you aren't already in one (screen -dr will reconnect you to a previous screen). Navigate to your NCBIdata directory.

\hypertarget{r}{%
\section{R}\label{r}}

The R Project for Statistical Computing

\url{https://www.r-project.org/}

R studio (Integrated Development Environment)

\url{https://posit.co/download/rstudio-desktop/}

\hypertarget{ggplot2}{%
\section{ggplot2}\label{ggplot2}}

Handy gglot2 references:

ggplot2 gallery

\url{http://www.r-graph-gallery.com/portfolio/ggplot2-package/}

ggplot2 cheatsheets

\url{http://ggplot2.tidyverse.org/reference/}

ggplot2 documentation

\url{https://cran.r-project.org/web/packages/ggplot2/ggplot2.pdf}

\hfill\break

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Make a tab-delimitted text file with the information from your sequence headers.
\end{enumerate}

\begin{verbatim}
1) Grab the sequence headers
2) Remove the greater than sign at the beginning of the header line
3) Replace the pipes with tabs (Hint: In sed use \t to represent a tab)
4) Make the date numeric by replacing the dashes. The sed command below will allow you to replace dashes only in the date.
\end{verbatim}

If you are interested in understanding the sed command: It looks for one or more (+) numbers ({[}0-9{]}) then a dash, more numbers, a dash and more numbers. The parentheses capture the sets of numbers so that it can return them as \textbackslash1 for the first set, \textbackslash2 for the second set, and \textbackslash3 for the third set.

\begin{verbatim}
sed -E 's/([0-9]+)-([0-9]+)-([0-9]+)/\1\2\3/'
5) Put it into a file called Denmark_Norway_Sweden_seq_info.txt
\end{verbatim}

The R environment on logrus needs to be activated (note that on some systems it is installed differently and you don't need to activate).

\begin{verbatim}
source activate visualization
\end{verbatim}

Open up R.

\begin{verbatim}
R
\end{verbatim}

Now we are in R. The R command line is similar to linux but the commands are a little bit different as you will notice as we walk through it. Note that you can use the up arrow to get back previous commands as in linux. ctrl-c works the same as well.

Load the ggplot2 library.

\begin{verbatim}
library(ggplot2)
\end{verbatim}

See what your working directory is (it should be the directory you were in when you entered R). Note that you can change your working directory with the setwd() command, putting the path to the new directory in the parentheses.

\begin{verbatim}
getwd()
\end{verbatim}

Let's read in the tab-delimitted file we created. We'll use the read.table command. To find out more, let's look at the help for that command using a question mark before the command (equivalent to the man command in linux).

\begin{verbatim}
?read.table
\end{verbatim}

It prints out a lot of documentation including commands that are similar. The first part is below. The help documentation describes the command and gives you all the arguments you can use along with their defaults. Arguments go in the parentheses. Some are required but others are optional.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\item
  The two arguments that I use the most are ``header'' and ``sep''. Look at the usage section of the help below or in your terminal. What are the defaults for these two arguments?
\item
  Scroll down in the help (the up and down arrows go up or down line by line; the space bar jumps you down a page at a time) to the arguments section. Read about header and sep. What do these arguments do? What do the defaults mean?
\end{enumerate}

Note: To get out of help, hit ``q''.

Read in our data file and put it into a variable. We'll name our variable dns for Denmark, Norway, Sweden.

\begin{verbatim}
dns = read.table("Denmark_Norway_Sweden_seq_info.txt", header=FALSE, sep="\t")
\end{verbatim}

Let's take a look at the variable with our data The head command in R has 6 rows by default and it wraps lines as a group if they are too long for the screen.

\begin{verbatim}
head(dns)
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\item
  Take a look at the help for the head command and see if you can figure out how to show 10 lines.
\item
  How do you think you could look at the end of the dns variable?
\end{enumerate}

When you look at the dns variable, it shows column and row names. Since we didn't have a header line in our tab-delimitted file, it just defaults to V1, V2 (V stands for vector). Since we didn't have row names, it defaults to numbers. Let's fix the column names. The ``c'' concatenates a list of things together to be fed in as a group.

\begin{verbatim}
colnames(dns) = c("Accession", "Genbank_Title", "Collection_Date", "Country", "GEO_Location", "Length", "Pangolin_Variant", "SRA_Accession", "Sequence_Type")
\end{verbatim}

Then check it with the head command.

\begin{verbatim}
    Accession
1 OR079912.1
2 OQ843561.1
3 OQ816151.1
4 OQ816152.1
5 OQ816154.1
6 OQ816156.1
                                                                                                           Genbank Title
1                  Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/NOR/P9/2020, complete genome
2             Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/DNK/DK-AHH8/2022, complete genome
3 Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/SWE/01_SE100_21CS503718/2020, complete genome
4 Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/SWE/01_SE100_21CS504474/2020, complete genome
5 Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/SWE/01_SE100_21CS503085/2020, complete genome
6 Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/SWE/01_SE100_21CS502014/2020, complete genome
  Collection Date Country GEO Location Length Pangolin Variant SRA Accession
1      2020-10-14  Norway       Norway  29825          B.1.258
2      2022-12-01 Denmark      Denmark  29752        BQ.1.1.20
3      2020-03-03  Sweden       Sweden  29736              B.1
4      2020-03-10  Sweden       Sweden  29736              B.1
5      2020-03-11  Sweden       Sweden  29736              B.1
6      2020-03-13  Sweden       Sweden  29736              B.1
  Sequence Type
1       GenBank
2       GenBank
3       GenBank
4       GenBank
5       GenBank
6       GenBank
\end{verbatim}

\hfill\break

The Collection Date wasn't recognized as numeric so let's fix that. The \$ after the dns refers to a column. We will just overwrite it in the same column.

\begin{verbatim}
dns$"Collection_Date" = as.numeric(dns$"Collection_Date")
\end{verbatim}

Time to plot!

The gglot2 library allows you to have a large amount of control over nearly all aspects of the plot. It also allows you to plot in layers, getting a base plot and then adding colors, lines, text, etc on top of it. It is part of the tidyverse universe and uses a Layered Grammar of Graphics (\url{https://towardsdatascience.com/a-comprehensive-guide-to-the-grammar-of-graphics-for-effective-visualization-of-multi-dimensional-1f92b4ed4149} and \url{https://www.jstor.org/stable/pdf/25651297.pdf?casa_token=KAMBWbsPZdwAAAAA:VHQTVEC762l7U6s6GWzRlYJNz5JaqfduQy1S04_LF6f3PUZjAh71Bva7WEIpROPBUx2BF9GL5bM0HOtDH_Zft81ycAcJ0971YeHDfrfHKBrgyw6G6fAG}) to concisely describe graphical components that are shared across different graphs. In other words, it gives you tools to add and manipulate specific pieces of graphical output.

We will put each plot into a png file. Note that we can also put it into a pdf file by changing the code below to pdf. The pdf has the advantage of being able to put in multiple plots on separate pages. After plotting we need to use dev.off() so that R closes the file it is printing to.

\hypertarget{histogram-of-collection-dates}{%
\subsection{Histogram of Collection Dates}\label{histogram-of-collection-dates}}

\begin{verbatim}
png("dates_histogram.png")

ggplot(dns, aes(x=Collection_Date)) + geom_histogram()

dev.off()
\end{verbatim}

\includegraphics[width=0.5\textwidth,height=\textheight]{./Figures/dates_histogram.png}

\hypertarget{plot-length-x-variants}{%
\subsection{Plot Length x Variants}\label{plot-length-x-variants}}

Let's plot the genome length by the variant to see if there are any patterns. Some variants have insertions or deletions compared to others, for instance. On the other hand, not all genome assemblies make it to the ends of the viral RNA genome so this will add some noise.

We'll use a scatter plot. First we identify the data frame (dns) that we want to use. Then we assign fields to the x and y axis. After that we'll add the scatter plot layer (geom\_point). We'll add another layer to limit the x axis.

\begin{verbatim}
png("lengthxvariants.png")

ggplot(dns, aes(x=Length,y=Pangolin_Variant)) + geom_point() + xlim(29500,30000)

dev.off()
\end{verbatim}

\includegraphics[width=0.5\textwidth,height=\textheight]{./Figures/lengthxvariants.png}

Now, let's color the points by Country.

\begin{verbatim}
png("lengthxvariants.color.png")

ggplot(dns, aes(x=Length,y=Pangolin_Variant,color=Country)) + geom_point() + xlim(29500,30000)

dev.off()
\end{verbatim}

\includegraphics[width=0.5\textwidth,height=\textheight]{./Figures/lengthxvariants.color.png}

\hypertarget{plot-collection-date-x-variants}{%
\subsection{Plot Collection Date x Variants}\label{plot-collection-date-x-variants}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{15}
\tightlist
\item
  Now try to plot the collection date (x axis) by the variants (y axis), coloring by the country.
\end{enumerate}

\hypertarget{plot-collection-date-x-variants-for-your-3-countries}{%
\subsection{Plot Collection Date x Variants for your 3 countries}\label{plot-collection-date-x-variants-for-your-3-countries}}

Now make a plot of Collection Date x Variants for your 3 countries and add it to your powerpoint.

Go to \url{https://covariants.org/} to scroll down to the table and the phylogenetic tree to put some context around the variants.

At that same site, explore the ``per country'' and ``cases'' buttons for your 3 countries. Note that the graphs are interactive so you can hover over specific dates where you might have a lot of NCBI genome sequences. Grab screenshots to put into your powerpoint (be sure to record the date you grabbed the screenshot on the slide). How representative are the NCBI genome sequences?

Note: we'll be getting sequences from another source as well so don't worry if they aren't too representative.

Click for All Answers

\begin{verbatim}
11. grep '>' sequences.fasta | sed 's/>//'|sed 's/|/\t/g'|sed -E 's/([0-9]+)-([0-9]+)-([0-9]+)/\1\2\3/' > Denmark_Norway_Sweden_seq_info.txt

12. header = FALSE and sep = ""

13. The header arguement determines whether you have a header line in your file with the names of variables.

While the header default is false, if you don't explicitly put in header=FALSE, it might decide that there is a header line if the first row has one fewer field than the rest. I like to explicitly tell read.table whether there is a header row or not.

The sep variable determines the field separator character.

The sep default is blank ("") and means white space. In other words, read.table will split the file up on one or more spaces, tabs, etc. With tab-delimitted files, you don't normally have to specify the tab variable but since we also have spaces in some of our fields, if we keep sep as whitespace, it will separate on all the spaces as well. So we will need to specify it.

14. head(dns, n=10) or head(dns, n=10L)

15. tail(dns)

16.

png("datexvariants.color.png")

ggplot(dns, aes(x=Collection_Date,y=Pangolin_Variant,color=Country)) + geom_point()

dev.off()
\end{verbatim}

\hypertarget{acknowledgements}{%
\chapter{Acknowledgements}\label{acknowledgements}}

This publication was supported by an Institutional Development Award (IDeA) from the National Institute of General Medical Sciences of the National Institutes of Health under grant number P20GM103451. Additional support came from National Science Foundation Award numbers 1759522 (Collaborative Research: Innovation: Pioneering New Approaches to Explore Pangenomic Space at Scale) and 2105391 (CRII: III: Toward the Compression of Pangenomic DNA Sequence Data Using Context-Free Grammars).

\includegraphics[width=0.5\textwidth,height=\textheight]{./Figures/INBRE_Logo_Grad_transparent-2019.png}

\includegraphics[width=0.5\textwidth,height=\textheight]{./Figures/ncgr.png}

\hypertarget{license-and-copyright-1}{%
\chapter{License and Copyright}\label{license-and-copyright-1}}

Creative Commons Attribution-NonCommercial-NoDerivatives 4.0
\url{https://creativecommons.org/licenses/by-nc-nd/4.0/}

© 2023 National Center for Genome Resources

  \bibliography{book.bib,packages.bib}

\end{document}
